export const STORES = [
  { name: "LAS MATAS", city: "Las Rozas de Madrid" },
  { name: "REYES CAT", city: "San Sebastián de los Reyes" },
  { name: "MAJADAHONDA I", city: "Majadahonda" },
  { name: "MONTE PILAR", city: "Majadahonda" },
  { name: "PARQUE PINAR", city: "Las Rozas de Madrid" },
  { name: "LA NAVATA", city: "Galapagar" },
  { name: "VILLALBA", city: "Collado Villalba" },
  { name: "GUADARRAMA", city: "Guadarrama" },
  { name: "VILLALBA PUEBLO", city: "Collado Villalba" },
  { name: "CERRO ESPINO", city: "Majadahonda" },
  { name: "MIRASIERRA", city: "Madrid" },
  { name: "PTA HIERRO", city: "Madrid" },
  { name: "PINEA", city: "Pozuelo de Alarcón" },
  { name: "MORALEJA GREEN", city: "Alcobendas" },
  { name: "ZIELO", city: "Pozuelo de Alarcón" },
  { name: "PASEO IMPERIAL", city: "Madrid" },
  { name: "TOLEDO", city: "Madrid" },
  { name: "VALLEHERMOSO", city: "Madrid" },
  { name: "CONDESA DE VENADITO", city: "Madrid" },
  { name: "MARQUES DE MONDEJAR", city: "Madrid" },
  { name: "NUÑEZ DE BALBOA", city: "Madrid" },
  { name: "PONZANO", city: "Madrid" },
  { name: "EMBAJADORES", city: "Madrid" },
  { name: "MARQUEZ DE LOZOYA", city: "Madrid" },
  { name: "NARVAEZ", city: "Madrid" },
  { name: "CLARA DEL REY", city: "Madrid" },
  { name: "DOCTOR FLEMING", city: "Madrid" },
  { name: "AVDA EUROPA", city: "Pozuelo de Alarcón" },
  { name: "AVDA COMUNIDAD MADRID", city: "Las Rozas de Madrid" },
  { name: "JR JIMENEZ", city: "Madrid" },
  { name: "RIVAS", city: "Rivas-Vaciamadrid" },
  { name: "SUANCES ALCALA 494", city: "Madrid" },
  { name: "ARAVACA", city: "Madrid" },
  { name: "LAS ROZAS", city: "Las Rozas de Madrid" },
  { name: "VALDEMARIN", city: "Madrid" },
  { name: "CASTELLO", city: "Madrid" },
  { name: "CASTELLANA", city: "Madrid" },
  { name: "CORAZON DE MARIA", city: "Madrid" },
  { name: "PALACIO DE HIELO", city: "Madrid" },
  { name: "QUINTANA", city: "Madrid" },
  { name: "VALDEBEBAS", city: "Madrid" },
  { name: "PINTO", city: "Pinto" },
  { name: "CEDIAL", city: "Madrid" },
  { name: "VILLANUEVA CAÑADA", city: "Villanueva de la Cañada" },
  { name: "VILLAVICIOSA", city: "Villaviciosa de Odón" },
  { name: "COLMENAR VIEJO", city: "Colmenar Viejo" },
  { name: "3 CANTOS", city: "Tres Cantos" },
  { name: "BARAJAS /CORONALES", city: "Madrid" },
  { name: "SAN SEBASTIAN REYES", city: "San Sebastián de los Reyes" },
  { name: "ALCOBENDAS", city: "Alcobendas" },
  { name: "MONTE CARMELO", city: "Madrid" },
  { name: "MARIA MAEZTU", city: "Madrid" },
  { name: "LAS TABLAS", city: "Madrid" },
  { name: "ARROYOFRESNO / CERRO M", city: "Madrid" },
  { name: "PRADO SOMOSAGUAS", city: "Pozuelo de Alarcón" },
  { name: "MONFORTE LEMOS", city: "Madrid" },
  { name: "ARTURO SORIA", city: "Madrid" },
  { name: "TORRELODONES", city: "Torrelodones" },
  { name: "MERCADO DE SAN ANTON", city: "Madrid" },
  { name: "BARQUILLO", city: "Madrid" },
  { name: "ODONNEL", city: "Madrid" },
  { name: "DIEGO DE LEON", city: "Madrid" },
  { name: "BOADILLA", city: "Boadilla del Monte" }
];

export const MUNICIPAL_HOLIDAYS = {
  "Alcobendas": { "01-24": "Ntra. Sra. de la Paz", "05-15": "San Isidro" },
  "Boadilla del Monte": { "05-26": "San Babilés", "10-06": "Ntra. Sra. del Rosario" },
  "Collado Villalba": { "06-13": "San Antonio de Padua", "07-24": "Santiago Apóstol" },
  "Colmenar Viejo": { "09-01": "Virgen de los Remedios (I)", "09-02": "Virgen de los Remedios (II)" },
  "Galapagar": { "05-15": "San Isidro", "09-15": "Stmo. Cristo de las Mercedes" },
  "Guadarrama": { "09-29": "San Miguel", "10-04": "San Francisco de Asís" },
  "Las Rozas de Madrid": { "05-05": "Ntra. Sra. del Retamar", "09-29": "San Miguel Arcángel" },
  "Madrid": { "05-15": "San Isidro", "11-10": "Ntra. Sra. de la Almudena" },
  "Majadahonda": { "09-14": "Stmo. Cristo de los Remedios", "11-25": "Santa Catalina" },
  "Pinto": { "03-19": "San José", "05-15": "San Isidro" },
  "Pozuelo de Alarcón": { "07-16": "Virgen del Carmen", "09-08": "Ntra. Sra. de la Consolación" },
  "Rivas-Vaciamadrid": { "05-15": "San Isidro", "05-16": "Fiestas Locales" },
  "San Sebastián de los Reyes": { "01-20": "San Sebastián", "08-28": "Stmo. Cristo de los Remedios" },
  "Torrelodones": { "07-16": "Virgen del Carmen", "08-14": "Asunción de la Virgen (Local)" },
  "Tres Cantos": { "03-21": "Aniversario de la Ciudad", "06-24": "San Juan" },
  "Villanueva de la Cañada": { "05-15": "San Isidro", "07-28": "San Ignacio de Loyola" },
  "Villaviciosa de Odón": { "01-20": "San Sebastián", "09-22": "Stmo. Cristo del Milagro" }
};
